import { WindowInformation } from './WindowInformation';
/**
 * Cluster, Dashboard and MapTemplate components will receive RootComponentInitialProps
 */
export interface RootComponentInitialProps {
  /**
   * id specified on Dashboard/MapTemplate or autogenerated id on Cluster
   */
  id: string;
  /**
   * react-native rootTag
   */
  rootTag: number;
  /**
   * this is the initial color scheme, use CarPlay.registerOnAppearanceDidChange to get updates on changes
   */
  colorScheme: 'dark' | 'light';
  window: WindowInformation;
}
